source "https://github.com/CocoaPods/Specs.git"
platform :ios, '8.0'
use_frameworks!

target "SocialContact" do

pod 'AFNetworking'
pod 'IQKeyboardManager'
#pod 'AMapLocation-NO-IDFA'
pod 'RSKImageCropper'
pod 'TZImagePickerController'
pod 'MJRefresh'
pod 'SVProgressHUD'
pod 'ZLSwipeableView'
pod 'SDCycleScrollView'
pod 'MJExtension'
pod 'KSPhotoBrowser'
pod 'TOCropViewController'
pod 'FDFullscreenPopGesture'
pod 'SwipeView'
pod 'CYLTabBarController'
pod 'Masonry'
pod 'DZNEmptyDataSet'
pod 'ZLSwipeableView'
pod 'CYLTabBarController'
pod 'AXWebViewController'
pod 'LCActionSheet'
pod 'JPush'
pod 'MBProgressHUD'
pod 'SDWebImage'
#pod 'RongCloudIM/IMLib'
pod 'RongCloudIM/IMKit'
pod 'CocoaSecurity'
pod 'LKDBHelper', '2.4.6'
pod 'Qiniu'
pod 'SCLAlertView-Objective-C'
pod 'AAPullToRefresh'
#pod 'JXCategoryView'
pod 'FLAnimatedImage'
pod 'AlipaySDK-iOS'
pod 'WechatOpenSDK'
#pod 'WRNavigationBar','~>1.2.0’
pod 'HHRefreshManager', '~> 1.1.1'
pod 'STPopup'
pod 'AXWebViewController'
pod 'KSPhotoBrowser'
pod 'YYKit'
pod 'TTTAttributedLabel'
#pod 'IAPHelper'
end
